name: "Setup Mono Repo"
description: "Setup tooling for mono repo"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"

    - run: npm install -g corepack@latest
      shell: bash

    - run: corepack enable pnpm
      shell: bash
